use crate::domain::{CommandProgram, CommandSpec, RiskClass};

pub const CATALOG: &[CommandSpec] = &[
    // Diagnostics
    CommandSpec {
        id: "aoxc-doctor",
        group: "AOXC Diagnostics",
        label: "Run AOXC Doctor",
        description: "Run platform readiness and dependency diagnostics.",
        risk: RiskClass::Low,
        program: CommandProgram::Aoxc,
        args: &["doctor"],
    },
    CommandSpec {
        id: "aoxc-version",
        group: "AOXC Diagnostics",
        label: "Check AOXC Version",
        description: "Display AOXC version and build metadata.",
        risk: RiskClass::Low,
        program: CommandProgram::Aoxc,
        args: &["version"],
    },
    CommandSpec {
        id: "aoxc-build-manifest",
        group: "AOXC Diagnostics",
        label: "Show Build Manifest",
        description: "Print AOXC build manifest for release audit.",
        risk: RiskClass::Low,
        program: CommandProgram::Aoxc,
        args: &["build-manifest"],
    },
    CommandSpec {
        id: "aoxc-policy",
        group: "AOXC Diagnostics",
        label: "Show Node Connection Policy",
        description: "Display AOXC node connection policy.",
        risk: RiskClass::Low,
        program: CommandProgram::Aoxc,
        args: &["node-connection-policy"],
    },
    // Chain and genesis flows
    CommandSpec {
        id: "aoxc-chain-create",
        group: "Chain and Genesis",
        label: "Create Chain",
        description: "Run guided chain creation from canonical AOXC entrypoint.",
        risk: RiskClass::Medium,
        program: CommandProgram::Aoxc,
        args: &["chain", "create"],
    },
    CommandSpec {
        id: "aoxc-chain-demo",
        group: "Chain and Genesis",
        label: "Create Demo Chain",
        description: "Provision demo chain workflow through AOXC.",
        risk: RiskClass::Medium,
        program: CommandProgram::Aoxc,
        args: &["chain", "demo"],
    },
    CommandSpec {
        id: "aoxc-genesis-verify",
        group: "Chain and Genesis",
        label: "Verify Genesis",
        description: "Run deterministic genesis verification.",
        risk: RiskClass::Low,
        program: CommandProgram::Aoxc,
        args: &["genesis", "verify"],
    },
    CommandSpec {
        id: "aoxc-genesis-sign",
        group: "Chain and Genesis",
        label: "Sign Genesis",
        description: "Sign genesis artifact with configured operator key.",
        risk: RiskClass::High,
        program: CommandProgram::Aoxc,
        args: &["genesis", "sign"],
    },
    // Node and network
    CommandSpec {
        id: "aoxc-node-status",
        group: "Node Operations",
        label: "Node Status",
        description: "Inspect local node status and sync progress.",
        risk: RiskClass::Low,
        program: CommandProgram::Aoxc,
        args: &["node", "status"],
    },
    CommandSpec {
        id: "aoxc-node-start",
        group: "Node Operations",
        label: "Start Node",
        description: "Start local AOXC node process.",
        risk: RiskClass::High,
        program: CommandProgram::Aoxc,
        args: &["node", "start"],
    },
    CommandSpec {
        id: "aoxc-node-stop",
        group: "Node Operations",
        label: "Stop Node",
        description: "Stop local AOXC node process.",
        risk: RiskClass::High,
        program: CommandProgram::Aoxc,
        args: &["node", "stop"],
    },
    CommandSpec {
        id: "aoxc-network-status",
        group: "Network Operations",
        label: "Network Status",
        description: "Inspect network quorum and finality signals.",
        risk: RiskClass::Low,
        program: CommandProgram::Aoxc,
        args: &["network", "status"],
    },
    CommandSpec {
        id: "aoxc-network-verify",
        group: "Network Operations",
        label: "Network Verify",
        description: "Run network health and topology verification.",
        risk: RiskClass::Medium,
        program: CommandProgram::Aoxc,
        args: &["network", "verify"],
    },
    // Wallet, tx, staking
    CommandSpec {
        id: "aoxc-wallet-balance",
        group: "Wallet and Transactions",
        label: "Wallet Balance",
        description: "Show wallet balances for the active environment.",
        risk: RiskClass::Low,
        program: CommandProgram::Aoxc,
        args: &["wallet", "balance"],
    },
    CommandSpec {
        id: "aoxc-wallet-create",
        group: "Wallet and Transactions",
        label: "Create Wallet",
        description: "Create wallet and deterministic address material.",
        risk: RiskClass::Medium,
        program: CommandProgram::Aoxc,
        args: &["wallet", "create"],
    },
    CommandSpec {
        id: "aoxc-tx-transfer",
        group: "Wallet and Transactions",
        label: "Transfer",
        description: "Submit value transfer transaction.",
        risk: RiskClass::High,
        program: CommandProgram::Aoxc,
        args: &["tx", "transfer"],
    },
    CommandSpec {
        id: "aoxc-stake-delegate",
        group: "Wallet and Transactions",
        label: "Delegate Stake",
        description: "Submit stake delegation transaction.",
        risk: RiskClass::High,
        program: CommandProgram::Aoxc,
        args: &["stake", "delegate"],
    },
    // Runtime and audit
    CommandSpec {
        id: "aoxc-runtime-verify",
        group: "Runtime and Audit",
        label: "Verify Runtime",
        description: "Verify runtime bundle and activation markers.",
        risk: RiskClass::Medium,
        program: CommandProgram::Aoxc,
        args: &["runtime", "verify"],
    },
    CommandSpec {
        id: "aoxc-audit-export",
        group: "Runtime and Audit",
        label: "Export Audit Bundle",
        description: "Export runtime and operator evidence package.",
        risk: RiskClass::Medium,
        program: CommandProgram::Aoxc,
        args: &["audit", "export"],
    },
    // Make-driven workspace operations
    CommandSpec {
        id: "make-build",
        group: "Workspace Operations",
        label: "Build Workspace",
        description: "Build workspace binaries using canonical Make workflow.",
        risk: RiskClass::Medium,
        program: CommandProgram::Make,
        args: &["build"],
    },
    CommandSpec {
        id: "make-test",
        group: "Workspace Operations",
        label: "Run Workspace Tests",
        description: "Execute workspace test suite through Make.",
        risk: RiskClass::Medium,
        program: CommandProgram::Make,
        args: &["test"],
    },
    CommandSpec {
        id: "make-check",
        group: "Workspace Operations",
        label: "Run Workspace Check",
        description: "Run compile-time check against workspace targets.",
        risk: RiskClass::Low,
        program: CommandProgram::Make,
        args: &["check"],
    },
    CommandSpec {
        id: "make-package-all-bin",
        group: "Packaging",
        label: "Package All Binaries",
        description: "Package all release binaries to AOXC bin location.",
        risk: RiskClass::High,
        program: CommandProgram::Make,
        args: &["package-all-bin"],
    },
    CommandSpec {
        id: "make-build-release-matrix",
        group: "Packaging",
        label: "Build Release Matrix",
        description: "Build dedicated mainnet/testnet/devnet release artifacts.",
        risk: RiskClass::High,
        program: CommandProgram::Make,
        args: &["build-release-matrix"],
    },
    CommandSpec {
        id: "make-publish-release",
        group: "Packaging",
        label: "Publish Release Evidence",
        description: "Create release archive and generate publication evidence.",
        risk: RiskClass::High,
        program: CommandProgram::Make,
        args: &["publish-release"],
    },
    CommandSpec {
        id: "make-db-init-sqlite",
        group: "State and Memory",
        label: "Init SQLite Memory",
        description: "Initialize sqlite-backed AOXC operator memory and runtime db.",
        risk: RiskClass::Medium,
        program: CommandProgram::Make,
        args: &["db-init-sqlite"],
    },
    CommandSpec {
        id: "make-db-status-sqlite",
        group: "State and Memory",
        label: "SQLite Memory Status",
        description: "Inspect sqlite-backed autonomous operator memory state.",
        risk: RiskClass::Low,
        program: CommandProgram::Make,
        args: &["db-status-sqlite"],
    },
    // Environment scoped operations
    CommandSpec {
        id: "mainnet-start",
        group: "Mainnet Operations",
        label: "Start Mainnet",
        description: "Start mainnet daemon flow via canonical Make target.",
        risk: RiskClass::High,
        program: CommandProgram::Make,
        args: &["net-mainnet-start"],
    },
    CommandSpec {
        id: "mainnet-status",
        group: "Mainnet Operations",
        label: "Mainnet Status",
        description: "Query current mainnet daemon status.",
        risk: RiskClass::Low,
        program: CommandProgram::Make,
        args: &["net-mainnet-status"],
    },
    CommandSpec {
        id: "testnet-start",
        group: "Testnet Operations",
        label: "Start Testnet",
        description: "Start rolling testnet supervisor (provision + start).",
        risk: RiskClass::High,
        program: CommandProgram::Make,
        args: &["aoxc-q-up"],
    },
    CommandSpec {
        id: "testnet-status",
        group: "Testnet Operations",
        label: "Testnet Status",
        description: "Query rolling testnet supervisor/node status.",
        risk: RiskClass::Low,
        program: CommandProgram::Make,
        args: &["aoxc-q-status"],
    },
    CommandSpec {
        id: "testnet-verify-full",
        group: "Testnet Operations",
        label: "Testnet Verify Full",
        description: "Run full runtime verify (rpc/api/query/faucet).",
        risk: RiskClass::Medium,
        program: CommandProgram::Make,
        args: &["aoxc-q-verify-full"],
    },
    // UI targets
    CommandSpec {
        id: "ui-mainnet",
        group: "Control Surface",
        label: "Launch UI Mainnet",
        description: "Run AOXCHub control surface in mainnet profile.",
        risk: RiskClass::Medium,
        program: CommandProgram::Make,
        args: &["ui-mainnet"],
    },
    CommandSpec {
        id: "ui-testnet",
        group: "Control Surface",
        label: "Launch UI Testnet",
        description: "Run AOXCHub control surface in testnet profile.",
        risk: RiskClass::Medium,
        program: CommandProgram::Make,
        args: &["ui-testnet"],
    },
];

pub fn find(id: &str) -> Option<&'static CommandSpec> {
    CATALOG.iter().find(|c| c.id == id)
}
