x-node-common: &node-common
  image: aoxchain-node:local
  build:
    context: .
    dockerfile: Dockerfile
  command: ["node-bootstrap"]
  init: true

services:
  node1:
    <<: *node-common
    ports:
      - "26656:26656"
      - "8545:8545"

  node2:
    <<: *node-common
    ports:
      - "26657:26656"
      - "8546:8545"

  node3:
    <<: *node-common
    ports:
      - "26658:26656"
      - "8547:8545"

  node4:
    <<: *node-common
    ports:
      - "26659:26656"
      - "8548:8545"
