version: "3.9"
services:
  node1:
    build: .
    command: ["node-bootstrap"]
    ports:
      - "26656:26656"
      - "8545:8545"
  node2:
    build: .
    command: ["node-bootstrap"]
    ports:
      - "26657:26656"
      - "8546:8545"
  node3:
    build: .
    command: ["node-bootstrap"]
    ports:
      - "26658:26656"
      - "8547:8545"
  node4:
    build: .
    command: ["node-bootstrap"]
    ports:
      - "26659:26656"
      - "8548:8545"
