//! auth subsystem for AOXC-VMachine-QX1 Kernel v1.
pub mod constitution;
pub mod domains;
pub mod envelope;
pub mod hybrid;
pub mod identity;
pub mod nonce;
pub mod policy;
pub mod qrkf;
pub mod quantum;
pub mod recovery;
pub mod registry;
pub mod replay;
pub mod rotation;
pub mod scheme;
pub mod session;
pub mod signer;
pub mod threshold;
pub mod verifier;
