#!/usr/bin/env python3
"""Generate a workspace test inventory summary for AOXCHAIN."""

from __future__ import annotations

import json
import re
import subprocess
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
CRATES_DIR = REPO_ROOT / "crates"
TESTS_DIR = REPO_ROOT / "tests"
FUZZ_DIR = REPO_ROOT / "fuzz" / "fuzz_targets"
OUTPUT_JSON = REPO_ROOT / "artifacts" / "testing" / "test_inventory.json"
OUTPUT_MD = REPO_ROOT / "docs" / "testing" / "TEST_MATRIX.md"

TEST_PATTERNS = [
    re.compile(r"#\[\s*test\s*\]"),
    re.compile(r"#\[\s*tokio::test(?:\([^\)]*\))?\s*\]"),
]
PROP_PATTERNS = [re.compile(r"\bproptest!\b"), re.compile(r"\bquickcheck!\b")]



def count_patterns(target: Path, patterns: list[re.Pattern[str]]) -> int:
    total = 0
    for path in target.rglob("*.rs"):
        text = path.read_text(encoding="utf-8")
        total += sum(len(pattern.findall(text)) for pattern in patterns)
    return total


def crate_test_counts() -> dict[str, int]:
    counts: dict[str, int] = {}
    for cargo_toml in sorted(CRATES_DIR.glob("*/Cargo.toml")):
        crate_root = cargo_toml.parent
        crate_name = crate_root.name
        counts[crate_name] = count_patterns(crate_root, TEST_PATTERNS)
    return counts


def collect_inventory() -> dict[str, object]:
    crate_counts = crate_test_counts()
    workspace_integration_tests = count_patterns(TESTS_DIR, TEST_PATTERNS) if TESTS_DIR.exists() else 0
    property_tests = count_patterns(REPO_ROOT, PROP_PATTERNS)
    fuzz_targets = len(list(FUZZ_DIR.glob("*.rs"))) if FUZZ_DIR.exists() else 0
    total_unit_like = sum(crate_counts.values())

    return {
        "generated_at_utc": datetime.now(timezone.utc).isoformat(),
        "counts": {
            "crate_scoped_tests": total_unit_like,
            "workspace_integration_tests": workspace_integration_tests,
            "property_macro_entries": property_tests,
            "fuzz_targets": fuzz_targets,
            "total_visible_test_entries": total_unit_like
            + workspace_integration_tests
            + property_tests,
        },
        "crate_scoped_tests": crate_counts,
    }


def render_markdown(inventory: dict[str, object]) -> str:
    counts = inventory["counts"]
    crate_counts: dict[str, int] = inventory["crate_scoped_tests"]  # type: ignore[assignment]

    lines: list[str] = []
    lines.append("# Test Matrix")
    lines.append("")
    lines.append(
        "This document is generated by `scripts/testing/generate_test_inventory.py` and summarizes visible validation surfaces in the repository."
    )
    lines.append("")
    lines.append(f"Generated at (UTC): `{inventory['generated_at_utc']}`")
    lines.append("")
    lines.append("## Inventory Summary")
    lines.append("")
    lines.append(f"- Crate-scoped test entries: **{counts['crate_scoped_tests']}**")
    lines.append(f"- Workspace integration test entries (`tests/`): **{counts['workspace_integration_tests']}**")
    lines.append(f"- Property-test macro entries (`proptest!/quickcheck!`): **{counts['property_macro_entries']}**")
    lines.append(f"- Fuzz targets (`fuzz/fuzz_targets/*.rs`): **{counts['fuzz_targets']}**")
    lines.append(f"- Total visible entries (test + property markers): **{counts['total_visible_test_entries']}**")
    lines.append("")
    lines.append("## Crate-Scoped Test Distribution")
    lines.append("")
    lines.append("| Crate | Test entries |")
    lines.append("| --- | ---: |")
    for crate_name, count in sorted(crate_counts.items()):
        lines.append(f"| `{crate_name}` | {count} |")
    lines.append("")
    lines.append("## Notes")
    lines.append("")
    lines.append("- This inventory is static-pattern based and intentionally conservative.")
    lines.append("- A counted entry is not a claim of pass/fail, only visibility in source.")
    lines.append("- Run `make test-inventory` to refresh this file and the JSON artifact.")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    inventory = collect_inventory()
    OUTPUT_JSON.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_JSON.write_text(json.dumps(inventory, indent=2, sort_keys=True) + "\n", encoding="utf-8")

    markdown = render_markdown(inventory)
    OUTPUT_MD.write_text(markdown, encoding="utf-8")

    print(f"Wrote {OUTPUT_JSON.relative_to(REPO_ROOT)}")
    print(f"Wrote {OUTPUT_MD.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
